name: qutils
description: A comprehensive utility package for Dart/Flutter with datetime, conversion, file info, QR code, JSON, and color utilities.
version: 1.0.3
homepage: https://vignaraj.dev
repository: https://github.com/vignarajj/qutils

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  mime: ^2.0.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.25.15
